---
config:
  theme: base
  look: neo
  layout: elk
  elk:
    nodePlacementStrategy: NETWORK_SIMPLEX
  themeVariables:
    darkMode: true
    background: "#121212"
    primaryColor: "#005a7a"
    primaryBorderColor: "#121212"
    secondaryBorderColor:  "#121212"
    edgeLabelBackground: transparent
    labelTextColor: "#5DD3FC"
    clusterBkg: transparent
    clusterBorder: "#5DD3FC"
    noteBkgColor: "#F47D22"
    noteBorderColor: "#F47D22"
    noteTextColor: "#fff"
---
flowchart LR
    classDef ref fill:#F47D22
    classDef notestyle fill:#F47D22
    classDef notestyle stroke:#F47D22
    classDef terminal fill:#1099c9
    classDef terminal stroke:#1099c9
    classDef success fill:#299967
    classDef success stroke:#299967

    start([start]):::terminal
    nochange([no PR, exit]):::terminal
    subgraph GitHub entry
        gh_readme[/"GitHub README content"/]
    end
    subgraph bio.tools entry
        bt_name[/bio.tools name/]
        bt_id[/bio.tools id/]
        bt_tt[/bio.tools tool types/]
    end

    start --> gh_readme & bt_name & bt_tt

    gh_readme & bt_name & bt_tt --> bridge_badge[["create a badge for bridge (this tool)"]]
    subgraph extract and create badges
        bridge_badge --> bt_badge[["create a badge for the bio.tools id"]]
        bt_badge --> check_tt{"is bio.tools tool types list empty/None?"}
        check_tt -->|no| tt_badge[["create a badge for tool types"]]
        tt_badge --> extract_badges[["extract existing badged from GitHub README content"]]
        check_tt -->|yes| extract_badges
        extract_badges --> merge_badges[[combine and deduplicate existing and new badges]]
    end

    merge_badges --> try_title[[try to extract project title from GitHub README]]
    subgraph extract project title
        try_title --> title_found{has an existing title been found?}
        title_found -->|yes| use_title[use existing title]
        title_found -->|no| bt_title[use bio.tools name as a title]
    end

    use_title & bt_title --> content[["extract remaining content of GitHub README (without title and badges)"]]
    subgraph extract content
        content
    end

    content --> render[["Render the final README using a template:<br/>project title<br/>badges<br/>remaining original content"]]
    render --> diff{is the rendered README content different from GitHub README?}
    diff -->|no| nochange
    diff -->|yes| pr["create PR info: use rendered README as content of README.md"]
    pr --> return([return PR info]):::success
