[cosmic-ray]
module-path = "src"
timeout = 45
test-command = "python -m pytest -q"
excluded-modules = [
  "bridge.core",
]

[[cosmic-ray.targets]]
module = "bridge"

[cosmic-ray.distributor]
name = "local"

# [cosmic-ray.distributor]
# name = "http"

# [cosmic-ray.distributor.http]
# worker-urls = [
#   "http://localhost:9876",
#   "http://localhost:9877",
#   "http://localhost:9878",
#   "http://localhost:9879",
#   "http://localhost:9880",
#   "http://localhost:9881",
#   "http://localhost:9882",
# ]