[project]
name = "bridge"
version = "0.1.0"
description = ""
authors = [
    {name = "Mariia Steeghs-Turchina"},
    {name = "Anna Niehues"},
    {name = "Veit Schwämmle"},
    {name = "Magnus Palmblad"},
    {name = "Ana Mendes"}
]
license = {text = "Apache-2.0"}
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "pydantic-core (>=2.41.4,<3.0.0)",
    "fastapi (>=0.120.4,<0.121.0)",
    "uvicorn (>=0.38.0,<0.39.0)",
    "pydantic-settings (>=2.11.0,<3.0.0)",
    "requests (>=2.32.5,<3.0.0)",
    "httpx (>=0.28.1,<0.29.0)",
    "typer (>=0.20.0,<0.21.0)",
    "huggingface-hub (>=1.0.1,<2.0.0)"
]

[tool.poetry.group.dev.dependencies]
datamodel-code-generator = "^0.35.0"
ruff = "^0.14.2"
black = "^25.9.0"
pre-commit = "^4.3.0"

[tool.poetry.group.docs.dependencies]
sphinx = "^8.2.3"
sphinx-autodoc-typehints = "^3.5.2"
myst-parser = "^4.0.1"
sphinx-book-theme = "^1.1.4"
sphinx-automodapi = "^0.20.0"
grimp = "^3.12"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ["py312"]
extend-exclude = '''
(
  ^src/bridge/core/biotools\.py
)
'''

[tool.ruff]
target-version = "py312"
line-length = 120
extend-exclude = [
  "docs",
  "src/bridge/core/biotools.py",
]

[tool.ruff.lint]
select = ["F", "E", "W", "I", "B", "C4", "UP", "N", "D"]
ignore = [
  "D105", # magic methods
  "D107", # __init__
  "D200", # one-line docstring must be single line
  "D205", # blank line after summary
  "D400", # first line ends with period
]
per-file-ignores = { "**/__init__.py" = ["F401"] }

[tool.ruff.lint.isort]
known-first-party = ["bridge"]
combine-as-imports = true

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.poetry]
packages = [{ include = "bridge", from = "src" }]

[tool.poetry.scripts]
lint = "scripts.quality:lint"
fmt = "scripts.quality:fmt"
gen-biotools-models = "scripts.gen_biotools_models:main"
gen-docs = "scripts.gen_docs:main"
gen-diagrams = "scripts.gen_diagrams:main"
bridge = "bridge.__main__:main_app"


