[project]
name = "bridge"
version = "0.1.0"
description = ""
authors = [
    {name = "Mariia Steeghs-Turchina"},
    {name = "Anna Niehues"},
    {name = "Veit Schwämmle"},
    {name = "Magnus Palmblad"},
    {name = "Ana Mendes"}
]
license = {text = "Apache-2.0"}
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "pydantic-core (>=2.41.4,<3.0.0)",
    "fastapi (>=0.120.4,<0.121.0)",
    "uvicorn (>=0.38.0,<0.39.0)",
    "pydantic-settings (>=2.11.0,<3.0.0)",
    "requests (>=2.32.5,<3.0.0)",
    "httpx (>=0.28.1,<0.29.0)",
    "typer (>=0.20.0,<0.21.0)",
    "huggingface-hub (>=1.0.1,<2.0.0)",
    "numpy (>=2.3.4,<3.0.0)",
    "sphinxcontrib-mermaid (>=1.2.3,<2.0.0)"
]

[tool.poetry.group.dev.dependencies]
datamodel-code-generator = "^0.35.0"
ruff = "^0.14.2"
black = "^25.9.0"
pre-commit = "^4.3.0"
pytest = "^8.4.2"
pytest-asyncio = "^1.2.0"
pytest-httpx = "^0.35.0"
pytest-cov = "^7.0.0"
cosmic-ray = "^8.4.3"

[tool.poetry.group.docs.dependencies]
sphinx = "^8.2.3"
sphinx-autodoc-typehints = "^3.5.2"
myst-parser = "^4.0.1"
sphinx-book-theme = "^1.1.4"
sphinx-automodapi = "^0.20.0"
grimp = "^3.12"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = [
  "tests",
]

[tool.coverage.run]
source = ["bridge"]
branch = true
parallel = true

[tool.coverage.report]
skip_covered = false
show_missing = true
omit = [
  "*/tests/*",
  "*/__init__.py",
]
exclude_lines = [
  "pragma: no cover",
  "if TYPE_CHECKING:",
  "raise NotImplementedError",
]

[tool.poetry]
packages = [{ include = "bridge", from = "src" }]

[tool.poetry.scripts]
lint = "scripts.quality:lint"
fmt = "scripts.quality:fmt"
coverage-report = "scripts.quality:coverage_report"
cosmic-ray-report = "scripts.quality:cosmic_ray_report"
gen-biotools-models = "scripts.gen_models:generate_biotools_models"
gen-github-models = "scripts.gen_models:generate_github_models"
gen-docs = "scripts.gen_docs:main"
gen-diagrams = "scripts.gen_diagrams:main"
gen-process-diagrams = "scripts.gen_process_diagrams:main"
bridge = "bridge.__main__:main_app"


