"""
Auto-generated Pydantic models for the GitHub languages schema.
Do not edit this file manually — it is generated by `scripts/gen_models.py`
from the JSON schema at schemas/github_languages.json.
"""

# generated by datamodel-codegen:
#   filename:  github_languages.json
#   timestamp: 2025-11-06T19:27:53+00:00

from __future__ import annotations

from typing import Dict

from pydantic import RootModel


class Language(RootModel[Dict[str, int]]):
    root: Dict[str, int]
