"""
Auto-generates Pydantic models for the bio.tools schema from the JSON schema at
https://raw.githubusercontent.com/bio-tools/biotoolsSchema/refs/heads/v4-dev/biotools.schema.json.

Run via:
    poetry run gen-biotools-models
"""

import json
import re
import urllib.request
from pathlib import Path

from datamodel_code_generator import DataModelType, InputFileType, generate

SCHEMA_URL = "https://raw.githubusercontent.com/bio-tools/biotoolsSchema/refs/heads/v4-dev/biotools.schema.json"
SCHEMA_PATH = Path("schemas/biotools.json")
EXTRACTED_SCHEMA_PATH = Path("schemas/tool_root.json")
FILENAME = "biotools.py"
OUTPUT_FILE = Path("src/bridge/core/") / FILENAME


def download_schema():
    """Download the JSON schema from the specified URL."""
    print(f"Downloading schema from {SCHEMA_URL}")
    SCHEMA_PATH.parent.mkdir(parents=True, exist_ok=True)
    urllib.request.urlretrieve(SCHEMA_URL, SCHEMA_PATH)
    print(f"Saved schema to {SCHEMA_PATH}")


def extract_tool_definition():
    """Extract the root 'tool' definition from the full JSON schema."""
    print("Extracting root object from definitions")
    raw_schema = json.loads(SCHEMA_PATH.read_text())
    extracted = {
        "$schema": raw_schema.get("$schema", "http://json-schema.org/draft-04/schema#"),
        "title": "Tool",
        "type": "object",
        "$ref": "#/definitions/tool",
        "definitions": raw_schema.get("definitions", {}),
    }
    EXTRACTED_SCHEMA_PATH.write_text(json.dumps(extracted, indent=2))
    print(f"Extracted root to {EXTRACTED_SCHEMA_PATH}")


def generate_models():
    """Generate Pydantic models from the extracted JSON schema."""
    print(f"Generating Pydantic models into {OUTPUT_FILE}")
    if OUTPUT_FILE.exists():
        OUTPUT_FILE.unlink()

    kwargs = {
        "input_": EXTRACTED_SCHEMA_PATH,
        "input_file_type": InputFileType.JsonSchema,
        "output": OUTPUT_FILE,
        "output_model_type": DataModelType.PydanticV2BaseModel,
        "reuse_model": True,
    }

    generate(**kwargs)

    print("Model generation complete.")


def add_docstring():
    """Prepend a docstring to the generated models file."""
    docstring = f'''"""
Auto-generated Pydantic models for the bio.tools schema.
Do not edit this file manually — it is generated by `scripts/gen_biotools_models.py`
from the JSON schema at {SCHEMA_URL}.
"""\n'''

    content = OUTPUT_FILE.read_text()

    # prepend only if the file doesn't already contain the docstring
    if not content.lstrip().startswith('"""Auto-generated'):
        OUTPUT_FILE.write_text(docstring + "\n" + content)

    print("Docstring prepended.")


def relax_extra_field_validation():
    """Allow extra fields in generated Pydantic models by patching model_config."""
    content = OUTPUT_FILE.read_text()

    # handle both quoting styles
    content = re.sub(r"ConfigDict\(\s*extra=['\"]forbid['\"]\s*\)", "ConfigDict(extra='ignore')", content)
    content = re.sub(r"extra\s*=\s*['\"]forbid['\"]", "extra='ignore'", content)

    OUTPUT_FILE.write_text(content)
    print(f"Relaxed Pydantic model config in {OUTPUT_FILE.name} to extra='ignore'.")


def main():
    """Run all steps."""
    download_schema()
    extract_tool_definition()
    generate_models()
    add_docstring()
    relax_extra_field_validation()


if __name__ == "__main__":
    main()
