"""
Auto-generates Pydantic models for the bio.tools schema from the JSON schema at
https://raw.githubusercontent.com/bio-tools/biotoolsSchema/refs/heads/v4-dev/biotools.schema.json.

Run via:
    poetry run gen-biotools-models
"""

import json
import re
import urllib.request
from pathlib import Path

from datamodel_code_generator import DataModelType, InputFileType, generate


def download_schema(download_from: str, save_to: Path):
    """Download the JSON schema from the specified URL."""
    print(f"Downloading schema from {download_from}")
    save_to.parent.mkdir(parents=True, exist_ok=True)
    urllib.request.urlretrieve(download_from, save_to)
    print(f"Saved schema to {save_to}")


def extract_tool_definition(schema_path: Path, extracted_path: Path):
    """Extract the root 'tool' definition from the full JSON schema."""
    print("Extracting root object from definitions")
    raw_schema = json.loads(schema_path.read_text())
    extracted = {
        "$schema": raw_schema.get("$schema", "http://json-schema.org/draft-04/schema#"),
        "title": "Tool",
        "type": "object",
        "$ref": "#/definitions/tool",
        "definitions": raw_schema.get("definitions", {}),
    }
    extracted_path.write_text(json.dumps(extracted, indent=2))
    print(f"Extracted root to {extracted_path}")


def generate_models(schema_path: Path, output_file: Path):
    """Generate Pydantic models from the extracted JSON schema."""
    print(f"Generating Pydantic models into {output_file}")
    if output_file.exists():
        output_file.unlink()

    kwargs = {
        "input_": schema_path,
        "input_file_type": InputFileType.JsonSchema,
        "output": output_file,
        "output_model_type": DataModelType.PydanticV2BaseModel,
        "reuse_model": True,
    }

    generate(**kwargs)

    print("Model generation complete.")


def add_docstring(docstring: str, output_file: Path):
    """Prepend a docstring to the generated models file."""
    content = output_file.read_text()

    # prepend only if the file doesn't already contain the docstring
    if not content.lstrip().startswith('"""Auto-generated'):
        output_file.write_text(docstring + "\n" + content)

    print("Docstring prepended.")


def relax_extra_field_validation(output_file: Path):
    """Allow extra fields in generated Pydantic models by patching model_config."""
    content = output_file.read_text()

    # handle both quoting styles
    content = re.sub(r"ConfigDict\(\s*extra=['\"]forbid['\"]\s*\)", "ConfigDict(extra='ignore')", content)
    content = re.sub(r"extra\s*=\s*['\"]forbid['\"]", "extra='ignore'", content)

    output_file.write_text(content)
    print(f"Relaxed Pydantic model config in {output_file.name} to extra='ignore'.")


def generate_biotools_models(download_from: str | Path):
    """Generate bio.tools Pydantic models."""
    schema_url = "https://raw.githubusercontent.com/bio-tools/biotoolsSchema/refs/heads/v4-dev/biotools.schema.json"
    schema_path = Path("schemas/biotools.json")
    extracted_schema_path = Path("schemas/tool_root.json")
    filename = "biotools_test.py"
    output_file = Path("src/bridge/core/") / filename

    docstring = f'''"""
Auto-generated Pydantic models for the bio.tools schema.
Do not edit this file manually — it is generated by `scripts/gen_models.py`
from the JSON schema at {schema_url}.
"""\n'''

    download_schema(download_from=schema_url, save_to=schema_path)
    extract_tool_definition(schema_path=schema_path, extracted_path=extracted_schema_path)
    generate_models(schema_path=extracted_schema_path, output_file=output_file)
    add_docstring(docstring=docstring, output_file=output_file)
    relax_extra_field_validation(output_file=output_file)


def generate_github_models():
    """Generate GitHub Pydantic models."""
    schema_path = Path("schemas/github_repo.json")
    filename = "github.py"
    output_file = Path("src/bridge/core/") / filename

    docstring = f'''"""
Auto-generated Pydantic models for the GitHub repository schema.
Do not edit this file manually — it is generated by `scripts/gen_models.py`
from the JSON schema at {schema_path}.
"""\n'''

    generate_models(schema_path=schema_path, output_file=output_file)
    add_docstring(docstring=docstring, output_file=output_file)
    relax_extra_field_validation(output_file=output_file)
